version: '3.8'

services:
  db-tikuretentrance:
    image: postgres:latest
    container_name: db-tikuretentrance
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5436:5432' # Exposing port 5432 to allow external connections

  pgadmin:
    links:
      - db-tikuretentrance:db-tikuretentrance
    container_name: pgadmin-mela
    image: dpage/pgadmin4
    ports:
      - '8083:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - app-network

  tikuretentrance-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tikuretentrance-server
    ports:
      - '4636:4636'
    depends_on:
      - db-tikuretentrance
    environment:
      PSQL_HOST: db-tikuretentrance
      PSQL_PORT: ${PSQL_PORT}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DB: ${PSQL_DB}
    env_file:
      - .env
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
