version: '3.8'

services:
  db-tikuretentrance:
    image: postgres:15-alpine
    container_name: db-tikuretentrance
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PSQL_USER} -d ${PSQL_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  tikuretentrance-server:
    build:
      context: ../.. # Points to root of monorepo
      dockerfile: apps/server/Dockerfile
    container_name: tikuretentrance-server
    ports:
      - '4636:4636'
    depends_on:
      db-tikuretentrance:
        condition: service_healthy
    environment:
      PSQL_HOST: db-tikuretentrance
      PSQL_PORT: ${PSQL_PORT}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DB: ${PSQL_DB}
    env_file:
      - docker.env
    restart: unless-stopped

volumes:
  postgres_data:
  
networks:
  app-network:
    driver: bridge
