import { Book } from "./types";

export const books: Book[] = [
  // Mathematics
  {
    id: "math-g9",
    title: "Mathematics Grade 9",
    description: "Official Grade 9 Mathematics textbook covering key topics in algebra, geometry, and arithmetic.",
    grade: "grade-9",
    subject: "Mathematics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonuUF481lm0uR9PxOp3wUXjEsLI4QyHAkBbqfD",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC9gb2EOI8uZqeSw0R15jrKJzXHNgbxc2lGh3O",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC9gb2EOI8uZqeSw0R15jrKJzXHNgbxc2lGh3O",
    chapters: [
      "Further on Sets",
      "The Number System",
      "Solving Equations",
      "Solving Inequalities",
      "Introduction to Trigonometry",
      "Regular Polygons",
      "Congruency and Similarity",
      "Vectors in Two Dimensions",
      "Statistics and Probability"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 320,
    fileSize: "18.19 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "math-g10",
    title: "Mathematics Grade 10",
    description: "Official Grade 10 Mathematics textbook covering advanced algebra, geometry, and trigonometry.",
    grade: "grade-10",
    subject: "Mathematics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonlL5zlcy6FLtMDgqsOrEwX1mhJpGWuBZPYn4Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCqfOhdTZE3a0rPtbJV2sHuZACmqTD6hy97Gdn",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCqfOhdTZE3a0rPtbJV2sHuZACmqTD6hy97Gdn",
    chapters: [
      "Relations and Functions",
      "Polynomial Functions",
      "Exponential and Logarithmic Functions",
      "Trigonometric Functions",
      "Circles",
      "Solid Figures",
      "Coordinate Geometry"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "19.08 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "math-g11",
    title: "Mathematics Grade 11",
    description: "Official Grade 11 Mathematics textbook covering advanced calculus, algebra, and geometry.",
    grade: "grade-11",
    subject: "Mathematics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonhYdlJnT3Sa3D0qbfy2U1nPkvtWsuEgwd5IV9",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCHbymxy9TrUi9LPFvS62V8KzgGkMOXJcx0Bj1",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCHbymxy9TrUi9LPFvS62V8KzgGkMOXJcx0Bj1",
    chapters: [
      "Relations and Functions",
      "Rational Expression and Rational Functions",
      "Matrices",
      "Determinants and their properties",
      "Vectors",
      "Transformations of the plane",
      "Statistics",
      "Probability"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "22.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "math-g12",
    title: "Mathematics Grade 12",
    description: "Official Grade 12 Mathematics textbook covering advanced topics in algebra, calculus, and geometry.",
    grade: "grade-12",
    subject: "Mathematics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon166a8xCGuaMrEK8b97OlXsSzdjv4hkAUxeJq",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCsbkvHry2CKDGk0dtSWmPzaBuQxXJi5Nhr1Eo",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCsbkvHry2CKDGk0dtSWmPzaBuQxXJi5Nhr1Eo",
    chapters: [
      "Sequence and Series",
      "Introductions to Calculus",
      "Statistics"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "20.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // English
  {
    id: "eng-g9",
    title: "English Grade 9",
    description: "Official Grade 9 English textbook covering grammar, writing, reading comprehension, and literature.",
    grade: "grade-9",
    subject: "English",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon6ibGV11Zf7Hsk8DUhwa5legLrpBuMAy3nFiS",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC4nrRDoW90GmfSAyDpotqIX7OlxCUv1a2khVR",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC4nrRDoW90GmfSAyDpotqIX7OlxCUv1a2khVR",
    chapters: [
      "Living in Urban Areas",
      "Study Skills",
      "Traffic Accident",
      "National Parks",
      "Horticulture",
      "Poverty in Ethiopia",
      "Community Services",
      "Communicable Diseases",
      "Fairness and Equity",
      "The Internet"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "eng-g10",
    title: "English Grade 10",
    description: "Official Grade 10 English textbook covering grammar, writing, reading comprehension, and literature.",
    grade: "grade-10",
    subject: "English",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonyEpZFw1ZDQPx5IFmbJzBhN1T8YinMO2RvKEf",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCLRGlABMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCLRGlABMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    chapters: [
      "Population Growth",
      "Travel Behaviors",
      "Punctuality",
      "Tourist Attractions",
      "Honey Processing",
      "Migration",
      "Branding Ethiopia and National",
      "The Healing Power of Plants",
      "Multilingualism",
      "Digital Vs Satellite Television"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "eng-g11",
    title: "English Grade 11",
    description: "Official Grade 11 English textbook covering grammar, writing, reading comprehension, and literature.",
    grade: "grade-11",
    subject: "English",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonqJV0qPCSseEPDHBhMx8RiJ0Uy9Vr5GYkczdl",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCY5tmsiSoZfspXA1hVDC8dRm2kUB9uvNOSrWb",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCY5tmsiSoZfspXA1hVDC8dRm2kUB9uvNOSrWb",
    chapters: [
      "Environmental Hazards",
      "Civilization",
      "Causes of Road Traffic Accidents",
      "People and Natural Resources",
      "Irrigation",
      "Global Warming",
      "Patriotism",
      "Efficiency of Health Services",
      "Indigenous Conflict Resolution",
      "Artificial Intelligence",
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "eng-g12",
    title: "English Grade 12",
    description: "Official Grade 12 English textbook covering grammar, writing, reading comprehension, and literature.",
    grade: "grade-12",
    subject: "English",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonBHCyeHJyD1r4a8oPu6EOALvM0ckiKNjbTQJ5",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCwUFNrEPLatv3qh8oIlDJeb92OZcnTQ4EViYz",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCwUFNrEPLatv3qh8oIlDJeb92OZcnTQ4EViYz",
    chapters: [
      "Sustainable Development",
      "Time Management",
      "Evidence on Traffic Accident",
      "Natural Resource Management",
      "Mechanized Agriculture",
      "Green Economies",
      "National Pride",
      "Telemedicine",
      "Conflict Management"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Geography
  {
    id: "geo-g9",
    title: "Geography Grade 9",
    description: "Official Grade 9 Geography textbook covering physical geography, human geography, and map reading.",
    grade: "grade-9",
    subject: "Geography",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonPJDrjZMYTaBQDenvo2i39xbjSXwcslRzgCpt",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCuaJKrT5Fa6G12UtKiAh8d0ITePqpN7EZms4B",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCuaJKrT5Fa6G12UtKiAh8d0ITePqpN7EZms4B",
    chapters: [
      "Geological History And Topography Of Ethiopia",
      "Climate Of Ethiopia",
      "Natural Resource Base Of Ethiopia",
      "Population And Demographic Characteristics Of Ethiopia",
      "Major Economic And Cultural Activities In Ethiopia",
      "Human - Natural Environment Interactions In Ethiopia",
      "Contemporary Geographic Issues And Public Concerns In Ethiopia",
      "Geographic Inquiry Skills And Techniques"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 320,
    fileSize: "21.19 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "geo-g10",
    title: "Geography Grade 10",
    description: "Official Grade 10 Geography textbook covering advanced physical geography, economic geography, and environmental studies.",
    grade: "grade-10",
    subject: "Geography",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon5s74aIvK0Pw1F2z7qBZmfNreUQgSA5nXhdyj",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC2ZZRpS4zbYhlBUJCXe8PDMmTZk3pGHy9Idwo",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC2ZZRpS4zbYhlBUJCXe8PDMmTZk3pGHy9Idwo",
    chapters: [
      "Land-forms Of Africa",
      "Climate Of Africa",
      "Natural Resource Base Of Africa",
      "Population of Africa",
      "Major Economic and Cultural Activities of Africa",
      "Human - Natural Environment Interactions",
      "Geographic Issues And Public Concerns In Africa",
      "Geospatial Information And Data Processing"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 330,
    fileSize: "11.66 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "geo-g11",
    title: "Geography Grade 11",
    description: "Official Grade 11 Geography textbook covering advanced physical geography, economic geography, and environmental studies.",
    grade: "grade-11",
    subject: "Geography",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon87C2e10ahPs61p79rS4lCbezU23GBfdIoAqi",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCWu30g7fSnw7VqOU9zZJIa38QELexiBp2MoPF",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCWu30g7fSnw7VqOU9zZJIa38QELexiBp2MoPF",
    chapters: [
      "Formation of the Continents",
      "Climate Classification and Climate Regions of Our World",
      "Natural Resources and Conflicts Over Resources",
      "Global Population Dynamics and Challenges",
      "Geography and Economic Development",
      "Major Global Environmental Changes",
      "Geographic Issues and Public Concerns",
      "Geo-spatial Information and Data Processing"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "12.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "geo-g12",
    title: "Geography Grade 12",
    description: "Official Grade 12 Geography textbook covering advanced physical geography, economic geography, and environmental studies.",
    grade: "grade-12",
    subject: "Geography",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonWuGHpMsPM5NifXRbhpV09Jlnx6dz3HCtyPmw",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCqhigQpZE3a0rPtbJV2sHuZACmqTD6hy97Gdn",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCqhigQpZE3a0rPtbJV2sHuZACmqTD6hy97Gdn",
    chapters: [
      "Major Geological Processes Associated with Plate Tectonics",
      "Climate Change",
      "Management of Conflict Over Resources",
      "Population Policies Programs and The Environment",
      "Challenges of Economic Development",
      "Solutions to Environmental and Sustainablity Problems",
      "Contemporary Global Geographic Issues and Public Concerns",
      "Geographical Enquiry and Map Making"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "13.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Physics
  {

    id: "phy-g9",
    title: "Physics Grade 9",
    description: "Official Grade 9 Physics textbook covering basic concepts in mechanics, heat, light, and sound.",
    grade: "grade-9",
    subject: "Physics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonjtrdHA6XpZqglum0DUt2fPOzA13HYbhrCTk5",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCQfBgvq90JnGoIbVtPUXSQm52WKDfd6Tiyx43",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCQfBgvq90JnGoIbVtPUXSQm52WKDfd6Tiyx43",
    chapters: [
      "Physics and Human Society",
      "Physical Quantities",
      "Morion in a Straight Line",
      "Force, Work, Energy, and Power",
      "Simple Machines",
      "Mechanical Oscillation and Sound Wave",
      "Temperature and Thermometer"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "phy-g10",
    title: "Physics Grade 10",
    description: "Official Grade 10 Physics textbook covering advanced concepts in mechanics, heat, light, and sound.",
    grade: "grade-10",
    subject: "Physics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonXM5mKDHq9tLwn1SCQh6veo5dMrJDYOTZHzKW",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCwkBhvR6PLatv3qh8oIlDJeb92OZcnTQ4EViY",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCwkBhvR6PLatv3qh8oIlDJeb92OZcnTQ4EViY",
    chapters: [
      "Vector Quantities",
      "Uniformly Accelerated Motion",
      "Elasticity and Static Equilibrium of Rigid Body",
      "Static and Current Electricity",
      "Magnetism",
      "Electromagnetic Waves and Geometrical Optics"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "phy-g11",
    title: "Physics Grade 11",
    description: "Official Grade 11 Physics textbook covering advanced concepts in mechanics, heat, light, and sound.",
    grade: "grade-11",
    subject: "Physics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonl9Fn1Ly6FLtMDgqsOrEwX1mhJpGWuBZPYn4Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMHLF9glMKQDVz97SNsiJqGurTt2EaIywXbRx",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMHLF9glMKQDVz97SNsiJqGurTt2EaIywXbRx",
    chapters: [
      "Physics and Human Society",
      "Vectors",
      "Motion in one and two dimensions",
      "Dynamics",
      "Heat Conduction and Calorimetry",
      "Electrostatics and Electric Circuit",
      "Nuclear Physic"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "phy-g12",
    title: "Physics Grade 12",
    description: "Official Grade 12 Physics textbook covering advanced concepts in mechanics, heat, light, and sound.",
    grade: "grade-12",
    subject: "Physics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonO0pywx93AxHSTm5Dk0LM7JFX6QIaBNiVucjU",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCx4UEpS2Oor5JfVEwxPzHZF6bANu2DaQ08isS",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCx4UEpS2Oor5JfVEwxPzHZF6bANu2DaQ08isS",
    chapters: [
      "Application of physics in other fields ",
      "Two-dimensional motion ",
      "Fluid Mechanics",
      "Electromagnetism",
      "Basics of electronics"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // ICT
  {
    id: "ict-g9",
    title: "ICT Grade 9",
    description: "Official Grade 9 ICT textbook covering computer hardware, software, networking, and programming.",
    grade: "grade-9",
    subject: "ICT",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonjhw9C96XpZqglum0DUt2fPOzA13HYbhrCTk5",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCLVBsbQMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCLVBsbQMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    chapters: [
      "Organization of Files",
      "Computer Network",
      "Application Software",
      "Image Processing and Multimedia",
      "Information and Computer Security",
      "Fundamentals of Programming"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "ict-g10",
    title: "ICT Grade 10",
    description: "Official Grade 10 ICT textbook covering advanced computer hardware, software, networking, and programming.",
    grade: "grade-10",
    subject: "ICT",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonskhU0YK9nSywGpiR1sfCdDZt7uNlMKPk8Ac6",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCxqtE1vB2Oor5JfVEwxPzHZF6bANu2DaQ08is",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCxqtE1vB2Oor5JfVEwxPzHZF6bANu2DaQ08is",
    chapters: [
      "Organization of Files",
      "Computer Network",
      "Application Software",
      "Image Processing and Multimedia",
      "Information and Computer Security",
      "Fundamentals of Programming"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"

  },
  {

    id: "ict-g11",
    title: "ICT Grade 11",
    description: "Official Grade 11 ICT textbook covering advanced computer hardware, software, networking, and programming.",
    grade: "grade-11",
    subject: "ICT",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonHdEx1S68mk6YsiI1uXRlfd0H9BzeK8VgjOZh",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCAgUiCPm1QWfbqNcla7URLp8vs0ogw532IuGY",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCAgUiCPm1QWfbqNcla7URLp8vs0ogw532IuGY",
    chapters: [
      "Information Systems and Its Applications",
      "Emerging Technologies",
      "Database Management",
      "Web Development",
      "Hardware Troubleshooting and Preventive Maintenance",
      "Fundamentals of Programming"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "ict-g12",
    title: "ICT Grade 12",
    description: "Official Grade 12 ICT textbook covering advanced computer hardware, software, networking, and programming.",
    grade: "grade-12",
    subject: "ICT",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonhVxptJ3Sa3D0qbfy2U1nPkvtWsuEgwd5IV9Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCvQu9De9VpbzKWrRkjD3TXs2O8yxtSu5PZqN0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCvQu9De9VpbzKWrRkjD3TXs2O8yxtSu5PZqN0",
    chapters: [
      "Information Systems and Their Applications",
      "Emerging Technologies",
      "Database Management System",
      "Web Authoring",
      "Maintenance and Troubleshooting",
      "Fundamentals of Programming"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Biology
  {

    id: "bio-g9",
    title: "Biology Grade 9",
    description: "Official Grade 9 Biology textbook covering basic concepts in cell biology, genetics, and ecology.",
    grade: "grade-9",
    subject: "Biology",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon87D1IU0ahPs61p79rS4lCbezU23GBfdIoAqi",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCL2uRNPMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCL2uRNPMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    chapters: [
      "Introduction to Biology",
      "Characteristics and Classification of Organisms",
      "Cells",
      "Reproduction",
      "Human Health, Nutrition, and Disease",
      "Ecology"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "bio-g10",
    title: "Biology Grade 10",
    description: "Official Grade 10 Biology textbook covering advanced concepts in cell biology, genetics, and ecology.",
    grade: "grade-10",
    subject: "Biology",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonWyKEQbPM5NifXRbhpV09Jlnx6dz3HCtyPmw4",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCJJiVZ6YGleqZD3uXwVQ1HmAB2ghIoK8LjCrN",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCJJiVZ6YGleqZD3uXwVQ1HmAB2ghIoK8LjCrN",
    chapters: [
      "Sub-fields of Biology",
      "Plants",
      "Biochemical molecules",
      "Cell reproduction",
      "Human Biology",
      "Ecological interaction"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "bio-g11",
    title: "Biology Grade 11",
    description: "Official Grade 11 Biology textbook covering advanced concepts in cell biology, genetics, and ecology.",
    grade: "grade-11",
    subject: "Biology",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonMyVFKOoulvNQVLTqnDPa74buyR8EBUSYsrH1",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCElFqHTeLIuaK8OpUEwlNM5C1FRTkJZ0b2xnm",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCElFqHTeLIuaK8OpUEwlNM5C1FRTkJZ0b2xnm",
    chapters: [
      "Characteristics of animals",
      "Enzymes",
      "Genetics",
      "The human body systems",
      "Population and natural resources"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",

    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "bio-g12",
    title: "Biology Grade 12",
    description: "Official Grade 12 Biology textbook covering advanced concepts in cell biology, genetics, and ecology.",
    grade: "grade-12",
    subject: "Biology",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon78EnjQuXM8oBivR5lJeLqEfscSgphWtk0uPj",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC5tRXW8U94XsBygoGh3WFTNrkwZ28bPSp7caR",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC5tRXW8U94XsBygoGh3WFTNrkwZ28bPSp7caR",
    chapters: [
      "Application of Biology",
      "Micro-organisms",
      "Energy Transformation",
      "Evolution",
      "Human Body System",
      "Climate Change"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Chemistry

  {
    id: "chem-g9",
    title: "Chemistry Grade 9",
    description: "Official Grade 9 Chemistry textbook covering basic concepts in matter, atoms, and chemical reactions.",
    grade: "grade-9",
    subject: "Chemistry",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonKhdGHZmsNiblgp971nR5dZQMLachyWfeOojY",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCtbm3rSAzXJsGf6PKyWr21U5HCT7SMbuF89aO",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCtbm3rSAzXJsGf6PKyWr21U5HCT7SMbuF89aO",
    chapters: [
      "Chemistry and It's Importance",
      "Measurements and Scientific Methods",
      "Structure of the Atom",
      "Periodic Classification of Elements",
      "Checmical Bonding"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  {
    id: "chem-g10",
    title: "Chemistry Grade 10",
    description: "Official Grade 10 Chemistry textbook covering advanced concepts in matter, atoms, and chemical reactions.",
    grade: "grade-10",
    subject: "Chemistry",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonvMFcBqQWN4SU9fPxleuB8sh3oEQKrDY5nq2p",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMw30NNlMKQDVz97SNsiJqGurTt2EaIywXbRx",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMw30NNlMKQDVz97SNsiJqGurTt2EaIywXbRx",
    chapters: [
      "Chemical Reactions and Stoichiometry",
      "Solutions",
      "Important Inorganic Compounds",
      "Energy Changes and Electro-Chemistry",
      "Metals and Non-Metals",
      "Hydro-Carbons and Their Natural Sources"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "chem-g11",
    title: "Chemistry Grade 11",
    description: "Official Grade 11 Chemistry textbook covering advanced concepts in matter, atoms, and chemical reactions.",
    grade: "grade-11",
    subject: "Chemistry",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonbjtiYuVLIYCH9hoOaXyzr2n5mwtKuEx4lN8Z",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCyBMbWTKuBpl3j2NOHxcUw9q1ybeJigrh0PRW",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCyBMbWTKuBpl3j2NOHxcUw9q1ybeJigrh0PRW",
    chapters: [
      "Atomic Structure And Periodic Properties Of The Elements",
      "Chemical Bonding",
      "Physical State Of Matter",
      "Chemical Kinetics",
      "Chemical Equilibrium",
      "Some Important Oxygen - containing Organic Compounds"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  {
    id: "chem-g12",
    title: "Chemistry Grade 12",
    description: "Official Grade 12 Chemistry textbook covering advanced concepts in matter, atoms, and chemical reactions.",
    grade: "grade-12",
    subject: "Chemistry",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonyjL9yX91ZDQPx5IFmbJzBhN1T8YinMO2RvKE",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCEm3ypyLIuaK8OpUEwlNM5C1FRTkJZ0b2xnmH",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCEm3ypyLIuaK8OpUEwlNM5C1FRTkJZ0b2xnmH",
    chapters: [
      "Acid-Base Equilibria",
      "Electrochemistry",
      "Industrial Chemistry",
      "Polymers",
      "Introduction to Environmental Chemistry",
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Civics and Ethical Education
  {

    id: "civ-g9",
    title: "Civics and Ethical Education Grade 9",
    description: "Official Grade 9 Civics and Ethical Education textbook covering governance, rights, and responsibilities.",
    grade: "grade-9",
    subject: "Civics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonMytWBykulvNQVLTqnDPa74buyR8EBUSYsrH1",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCCCJj6Pvcgo9pPINwD7nZ21iY0jUkTVeCfmGz",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCCCJj6Pvcgo9pPINwD7nZ21iY0jUkTVeCfmGz",
    chapters: [
      "Ethical Values",
      "The Culture of Using Digital Technology",
      "Understanding Inndigenous Knowledge",
      "Multi-Culturalism in Ethiopia",
      "National Unity Through Diversity",
      "Problem-Solving Skills",
      "Ethiopia's Foreign Relations in East Africa"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "15.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "civ-g10",
    title: "Civics and Ethical Education Grade 10",
    description: "Official Grade 10 Civics and Ethical Education textbook covering governance, rights, and responsibilities.",
    grade: "grade-10",
    subject: "Civics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonhWTjuR3Sa3D0qbfy2U1nPkvtWsuEgwd5IV9Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCUMU8BEGeZ5tLdCkVrwcTpBn10HRMYNlPQ2ID",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCUMU8BEGeZ5tLdCkVrwcTpBn10HRMYNlPQ2ID",
    chapters: [
      "Democracy and Democratization",
      "Citizens in the Digital Technology Age",
      "Understanding Good Governance",
      "Peace and Indigenous Conflict Resolution Mechanisms",
      "Federalism in Africa",
      "Human Rights",
      "Partiotism",
      "Globalization and Global Issues"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "15.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  {

    id: "civ-g11",
    title: "Civics and Ethical Education Grade 11",
    description: "Official Grade 11 Civics and Ethical Education textbook covering governance, rights, and responsibilities.",
    grade: "grade-11",
    subject: "Civics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonZpCOUaVtNeArf0UXY4ObtwumDC2dJ9EclvaM",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC51AnvfU94XsBygoGh3WFTNrkwZ28bPSp7caR",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC51AnvfU94XsBygoGh3WFTNrkwZ28bPSp7caR",
    chapters: [
      "Building a Democratic System",
      "Rule of Law",
      "Equality",
      "Justice",
      "Patriotism",
      "Responsibility",
      "Industriousness",
      "Self-Reliance",
      "Saving",
      "Active Community Participation"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "civ-g12",
    title: "Civics and Ethical Education Grade 12",
    description: "Official Grade 12 Civics and Ethical Education textbook covering governance, rights, and responsibilities.",
    grade: "grade-12",
    subject: "Civics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon3cgXUd2JOPxv6d9XFKH2Iy1WTpG3MNEufmqU",
    downloadUrl: "/books/civ-g12.pdf",
    pdfUrl: "https://uploadthing.com/Grade12-civics.pdf",
    chapters: [
      "Building a Democratic System",
      "Rule of Law",
      "Equality",
      "Justice",
      "Patriotism",
      "Responsibility",
      "Industriousness",
      "Self-Reliance",
      "Saving",
      "Active Community Participation",
      "The Pursuit of Wisdom"
    ],
    recentlyViewed: true,

    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Economics
  {
    id: "eco-g9",
    title: "Economics Grade 9",
    description: "Official Grade 9 Economics textbook covering basic concepts in microeconomics and macroeconomics.",
    grade: "grade-9",
    subject: "Economics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon1vEKLaGuaMrEK8b97OlXsSzdjv4hkAUxeJqi",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCmDuExldHY7sW1efqpDQzLjZvCrxao35FyiRA",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCmDuExldHY7sW1efqpDQzLjZvCrxao35FyiRA",
    chapters: [
      "Introducing Economics",
      "The Basic Economic Problems and Economic Systems",
      "Economic Resources and Markets",
      "Introduction to Demand and Supply",
      "Introduction to Production and Cost",
      "Introduction to Money",
      "Introduction to Macroeconomics",
      "Basic Entrepreneurship"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "15.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "eco-g10",
    title: "Economics Grade 10",
    description: "Official Grade 10 Economics textbook covering advanced concepts in microeconomics and macroeconomics.",
    grade: "grade-10",
    subject: "Economics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonxEy3UaDc9jh47KXBGEAzTb8OJpqrgPVu1iLC",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCR5YoD9Cz9goqFQaSPpAxVvli27ycb6GnOIwT",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCR5YoD9Cz9goqFQaSPpAxVvli27ycb6GnOIwT",
    chapters: [
      "Theory of Consumer Behaviour",
      "Theories of Demand and Supply",
      "Theories of Production and Cost",
      "Market Structure",
      "Banking and Finance",
      "Economic Growth",
      "The Ethiopian Economy",
      "Business Startups and Innovation"
    ],
    recentlyViewed: true,

    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "eco-g11",
    title: "Economics Grade 11",
    description: "Official Grade 11 Economics textbook covering advanced concepts in microeconomics and macroeconomics.",
    grade: "grade-11",
    subject: "Economics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonuC68Bglm0uR9PxOp3wUXjEsLI4QyHAkBbqfD",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC6Dy4fMunqREUOwgtyz2NS1poruWV7Y6GF0a3",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC6Dy4fMunqREUOwgtyz2NS1poruWV7Y6GF0a3",
    chapters: [
      "Theory of Consumer Behavior and Demand",
      "Market Structure and The Decision of Firms",
      "National Income Accounting",
      "Consumption, Saving and Investment",
      "Trade and Finance",
      "Economic Development",
      "Main Sectors, Sectorial Policies and Strategies"
    ],
    recentlyViewed: true,

    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "eco-g12",
    title: "Economics Grade 12",
    description: "Official Grade 12 Economics textbook covering advanced concepts in microeconomics and macroeconomics.",
    grade: "grade-12",
    subject: "Economics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonhCqyFq3Sa3D0qbfy2U1nPkvtWsuEgwd5IV9Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC6Dy4fMunqREUOwgtyz2NS1poruWV7Y6GF0a3",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC6Dy4fMunqREUOwgtyz2NS1poruWV7Y6GF0a3",
    chapters: [
      "The Fundamental Concepts of Macro-Economics",
      "Aggregate Demand and Aggregate Supply Analysis",
      "Market Failure and Consumer Protection",
      "Macro-Economic Policy Instruments",
      "Tax Theory and Practice",
      "Poverty and Inequality",
      "Macro-Economic Reforms in Ethiopia",
      "Economy, Environment and Climate Change"
    ],
    recentlyViewed: true,

    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // History
  {
    id: "his-g9",
    title: "History Grade 9",
    description: "Official Grade 9 History textbook covering major events in world history and Ethiopian history.",
    grade: "grade-9",
    subject: "History",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonmH8KOG37gGwQ5PWeIdTkFrE96cfJbVL3Z1O2",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCHk6DYdTrUi9LPFvS62V8KzgGkMOXJcx0Bj1Z",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCHk6DYdTrUi9LPFvS62V8KzgGkMOXJcx0Bj1Z",
    chapters: [
      "The Discipline of History and Human Evolution",
      "Ancient World Civilizations up to c.500 AD",
      "Peoples and States in Ethiopia and the Horn to the End of 13th Century",
      "The Middle Ages and Early Modern World, C. 500 to 1750s",
      "Peoples and States of Africa to 1500",
      "Africa and the Outside World 1500-1880s",
      "States, Principalities, Population Movements &Interactions in Ethiopia 13th to Mid-16th C.",
      "Political, Social, and Economic Processes in Ethiopia Mid-16th to Mid-19th C.",
      "The Age of Revolutions 1750s to 1815",
      "The Discipline of History and Human Evolution",
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "9.66 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "his-g10",
    title: "History Grade 10",
    description: "Official Grade 10 History textbook covering key events in world and Ethiopian history from the 19th century.",
    grade: "grade-10",
    subject: "History",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTontS1SwmiXeYcgSNJGz2mDivfFloEPAV0pC4xh",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMy8UcgdlMKQDVz97SNsiJqGurTt2EaIywXbR",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMy8UcgdlMKQDVz97SNsiJqGurTt2EaIywXbR",
    chapters: [
      "Development of Capitalism and Nationalism 1815-1914",
      "Africa & the Colonial Experience(1880s -1960s)",
      "Social, Economic & Political Developments in Ethiopia mid-19th C. to 1941",
      "Society and Politics in the Age of World Wars 1914-1945",
      "Global and Regional Developments Since 1945",
      "Ethiopia: Internal Developments and External Influences from 1941 to 1991",
      "Africa Since 1960",
      "Post-1991 Developments in Ethiopia",
      "Indigenous Knowledge and Heritages of Ethiopia"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 320,
    fileSize: "11.28 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "his-g11",
    title: "History Grade 11",
    description: "Official Grade 11 History textbook covering world and Ethiopian history from the 20th century to present.",
    grade: "grade-11",
    subject: "History",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonsyZ7VFK9nSywGpiR1sfCdDZt7uNlMKPk8Ac6",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCvQ9biGPVpbzKWrRkjD3TXs2O8yxtSu5PZqN0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCvQ9biGPVpbzKWrRkjD3TXs2O8yxtSu5PZqN0",
    chapters: [
      "History, Historiography, and Human Evolution",
      "Major Spots of Ancient World Civilizations Up to c.500 A.D",
      "Peoples, States and Historical Processes in Ethiopia and The Horn to The End of The 13th Century",
      "The Middle Ages and Early Modern World, C. 500 AD-1789",
      "Peoples and States of Africa To 1500",
      "Africa and the Outside World: 1500-1800",
      "States, Principalities, Population Movements and Interactions in Ethiopia",
      "Political, Social, and Economic Processes in Ethiopia, Mid 16th to Mid-19th Century",
      "The Age of Revolutions, 1789 to 1815"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "12.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "his-g12",
    title: "History Grade 12",
    description: "Official Grade 12 History textbook covering advanced topics in world history, Ethiopia's history, and modern political studies.",
    grade: "grade-12",
    subject: "History",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonioOqv2p7TpzRtUysOSHYhKIw4rVPZeA9DXWm",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCJfQzf9YGleqZD3uXwVQ1HmAB2ghIoK8LjCrN",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCJfQzf9YGleqZD3uXwVQ1HmAB2ghIoK8LjCrN",
    chapters: [
      "Development of Capitalism and Nationalism from 1815 to 1914",
      "Africa and the Colonial Experience (1880s - 1960s)",
      "Social, Economic and Political Developments in Ethiopia, Mid, 19th C. to 1941",
      "Society and Politics in the Age of World Wars, 1914 - 1945",
      "Global and Regional Developments Since 1945",
      "Ethiopia: Internal Developments and External Influences from 1941 to 1991",
      "Africa since the 1960s",
      "Post 1991 Developments in Ethiopia",
      "Indigenous Knowledge Systems and Heritages of Ethiopia"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "14.0 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // HPE (Health and Physical Education)
  {
    id: "hpe-g9",
    title: "Health and Physical Education Grade 9",
    description: "Official Grade 9 Health and Physical Education textbook covering topics in physical fitness, health education, and personal well-being.",
    grade: "grade-9",
    subject: "HPE",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonvUaL51WN4SU9fPxleuB8sh3oEQKrDY5nq2pT",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC9B3BebI8uZqeSw0R15jrKJzXHNgbxc2lGh3O",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC9B3BebI8uZqeSw0R15jrKJzXHNgbxc2lGh3O",
    chapters: [
      "Sport and Society",
      "Health and Physical Fitness",
      "Athletics",
      "FootBall",
      "VolleyBall",
      "BasketBall",
      "HandBall",
      "Self-Defense and Sport Ethics"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 280,
    fileSize: "6.35 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "hpe-g10",
    title: "Health and Physical Education Grade 10",
    description: "Official Grade 10 Health and Physical Education textbook covering advanced topics in health, fitness, and physical activity.",
    grade: "grade-10",
    subject: "HPE",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonoF234tni8MIw0ugZWsQx7NBE5HDveRCLSt4n",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCsErtSEy2CKDGk0dtSWmPzaBuQxXJi5Nhr1Eo",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCsErtSEy2CKDGk0dtSWmPzaBuQxXJi5Nhr1Eo",
    chapters: [
      "Sport and Society",
      "Health and Physical Fitness",
      "Athletics",
      "FootBall",
      "VolleyBall",
      "BasketBall",
      "HandBall",
      "Self-Defense and Sport Ethics"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "9.48 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Amharic

  {
    id: "amh-g9",
    title: "Amharic Grade 9",
    description: "Official Grade 9 Amharic textbook covering reading, writing, and grammar.",
    grade: "grade-9",
    subject: "Amharic",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon01953zdtgsOSvlC3ZRu6mGwVNPdpoTJjUBLz",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCkV6Jnf7bvDXNE2ShaL1O07Plm8rTHzCVIKoi",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCkV6Jnf7bvDXNE2ShaL1O07Plm8rTHzCVIKoi",
    chapters: [
      "Unit 1: ቋንቋ",
      "Unit 2: ግብር",
      "Unit 3: ማዕድን ማውጣት",
      "Unit 4: ልቦለድ",
      "Unit 5: ቃላዊ ስነፅሑፍ",
      "Unit 6: ግጥም",
      "Unit 7: ኮቪድ -19 (ኮሮና)",
      "Unit 8: ተውኔት",
      "Unit 9: ማህበራዊ መገናኛ ብዙኃን እና ተግባቦት"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "Amharic",
    pages: 320,
    fileSize: "17.48 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "amh-g10",
    title: "Amharic Grade 10",
    description: "Official Grade 10 Amharic textbook covering advanced reading, writing, and grammar topics.",
    grade: "grade-10",
    subject: "Amharic",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonPzqYswMYTaBQDenvo2i39xbjSXwcslRzgCpt",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCXdorZDBkChtfvgWnwij7TOJbZLsMmeX50aY2",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCXdorZDBkChtfvgWnwij7TOJbZLsMmeX50aY2",
    chapters: [
      "ቋንቋና ማህበረሰብ",
      "ባህላዊ ጋብቻ",
      "ሴቶች እና እድገት",
      "በልዩነት ውስጥ ያለ አንድነት",
      "የቋንቋ ለዛ",
      "የታላላቆች ሚና",
      "ረጅም ልቦለድ",
      "ማህበራዊ መገናኛ ብዙኀን",
      "ሥራ ፈጠራ"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "Amharic",
    pages: 350,
    fileSize: "18.72 MB",
    curriculum: "Ethiopian Secondary Education"
  },
];
