import { Book } from "./types";

export const books: Book[] = [
  // Mathematics
  {
    id: "math-g9",
    title: "Mathematics Grade 9",
    description: "Official Grade 9 Mathematics textbook covering key topics in algebra, geometry, and arithmetic.",
    grade: "grade-9",
    subject: "Mathematics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonuUF481lm0uR9PxOp3wUXjEsLI4QyHAkBbqfD",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC9gb2EOI8uZqeSw0R15jrKJzXHNgbxc2lGh3O",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC9gb2EOI8uZqeSw0R15jrKJzXHNgbxc2lGh3O",
    chapters: [
      "Basic Algebra",
      "Geometry",
      "Trigonometry",
      "Statistics",
      "Probability"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 320,
    fileSize: "18.19 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "math-g10",
    title: "Mathematics Grade 10",
    description: "Official Grade 10 Mathematics textbook covering advanced algebra, geometry, and trigonometry.",
    grade: "grade-10",
    subject: "Mathematics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonlL5zlcy6FLtMDgqsOrEwX1mhJpGWuBZPYn4Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCqfOhdTZE3a0rPtbJV2sHuZACmqTD6hy97Gdn",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCqfOhdTZE3a0rPtbJV2sHuZACmqTD6hy97Gdn",
    chapters: [
      "Algebra",
      "Geometry",
      "Trigonometry",
      "Statistics",
      "Probability"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "19.08 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "math-g11",
    title: "Mathematics Grade 11",
    description: "Official Grade 11 Mathematics textbook covering advanced calculus, algebra, and geometry.",
    grade: "grade-11",
    subject: "Mathematics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonhYdlJnT3Sa3D0qbfy2U1nPkvtWsuEgwd5IV9",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCHbymxy9TrUi9LPFvS62V8KzgGkMOXJcx0Bj1",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCHbymxy9TrUi9LPFvS62V8KzgGkMOXJcx0Bj1",
    chapters: [
      "Advanced Algebra",
      "Calculus",
      "Vectors",
      "Geometry",
      "Matrices"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "22.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "math-g12",
    title: "Mathematics Grade 12",
    description: "Official Grade 12 Mathematics textbook covering advanced topics in algebra, calculus, and geometry.",
    grade: "grade-12",
    subject: "Mathematics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon166a8xCGuaMrEK8b97OlXsSzdjv4hkAUxeJq",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCsbkvHry2CKDGk0dtSWmPzaBuQxXJi5Nhr1Eo",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCsbkvHry2CKDGk0dtSWmPzaBuQxXJi5Nhr1Eo",
    chapters: [
      "Functions and Graphs",
      "Limits and Continuity",
      "Differentiation",
      "Integration",
      "Vectors in 3D"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "20.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // English
  {
    id: "eng-g9",
    title: "English Grade 9",
    description: "Official Grade 9 English textbook covering grammar, writing, reading comprehension, and literature.",
    grade: "grade-9",
    subject: "English",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon6ibGV11Zf7Hsk8DUhwa5legLrpBuMAy3nFiS",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC4nrRDoW90GmfSAyDpotqIX7OlxCUv1a2khVR",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC4nrRDoW90GmfSAyDpotqIX7OlxCUv1a2khVR",
    chapters: [
      "Grammar",
      "Vocabulary",
      "Writing Skills",
      "Reading Comprehension",
      "Literature"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "eng-g10",
    title: "English Grade 10",
    description: "Official Grade 10 English textbook covering grammar, writing, reading comprehension, and literature.",
    grade: "grade-10",
    subject: "English",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonyEpZFw1ZDQPx5IFmbJzBhN1T8YinMO2RvKEf",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCLRGlABMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCLRGlABMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    chapters: [
      "Grammar",
      "Vocabulary",
      "Writing Skills",
      "Reading Comprehension",
      "Literature"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "eng-g11",
    title: "English Grade 11",
    description: "Official Grade 11 English textbook covering grammar, writing, reading comprehension, and literature.",
    grade: "grade-11",
    subject: "English",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonqJV0qPCSseEPDHBhMx8RiJ0Uy9Vr5GYkczdl",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCY5tmsiSoZfspXA1hVDC8dRm2kUB9uvNOSrWb",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCY5tmsiSoZfspXA1hVDC8dRm2kUB9uvNOSrWb",
    chapters: [
      "Grammar",
      "Vocabulary",
      "Writing Skills",
      "Reading Comprehension",
      "Literature"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "eng-g12",
    title: "English Grade 12",
    description: "Official Grade 12 English textbook covering grammar, writing, reading comprehension, and literature.",
    grade: "grade-12",
    subject: "English",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonBHCyeHJyD1r4a8oPu6EOALvM0ckiKNjbTQJ5",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCwUFNrEPLatv3qh8oIlDJeb92OZcnTQ4EViYz",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCwUFNrEPLatv3qh8oIlDJeb92OZcnTQ4EViYz",
    chapters: [
      "Grammar",
      "Vocabulary",
      "Writing Skills",
      "Reading Comprehension",
      "Literature"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Geography
  {
    id: "geo-g9",
    title: "Geography Grade 9",
    description: "Official Grade 9 Geography textbook covering physical geography, human geography, and map reading.",
    grade: "grade-9",
    subject: "Geography",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonPJDrjZMYTaBQDenvo2i39xbjSXwcslRzgCpt",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCuaJKrT5Fa6G12UtKiAh8d0ITePqpN7EZms4B",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCuaJKrT5Fa6G12UtKiAh8d0ITePqpN7EZms4B",
    chapters: [
      "Physical Geography",
      "Human Geography",
      "Climate",
      "Population"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 320,
    fileSize: "21.19 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "geo-g10",
    title: "Geography Grade 10",
    description: "Official Grade 10 Geography textbook covering advanced physical geography, economic geography, and environmental studies.",
    grade: "grade-10",
    subject: "Geography",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon5s74aIvK0Pw1F2z7qBZmfNreUQgSA5nXhdyj",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC2ZZRpS4zbYhlBUJCXe8PDMmTZk3pGHy9Idwo",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC2ZZRpS4zbYhlBUJCXe8PDMmTZk3pGHy9Idwo",
    chapters: [
      "Physical Geography",
      "Economic Geography",
      "Environmental Issues",
      "Map Skills"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 330,
    fileSize: "11.66 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "geo-g11",
    title: "Geography Grade 11",
    description: "Official Grade 11 Geography textbook covering advanced physical geography, economic geography, and environmental studies.",
    grade: "grade-11",
    subject: "Geography",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon87C2e10ahPs61p79rS4lCbezU23GBfdIoAqi",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCWu30g7fSnw7VqOU9zZJIa38QELexiBp2MoPF",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCWu30g7fSnw7VqOU9zZJIa38QELexiBp2MoPF",
    chapters: [
      "Physical Geography",
      "Economic Geography",
      "Environmental Issues",
      "Map Skills"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "12.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "geo-g12",
    title: "Geography Grade 12",
    description: "Official Grade 12 Geography textbook covering advanced physical geography, economic geography, and environmental studies.",
    grade: "grade-12",
    subject: "Geography",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonWuGHpMsPM5NifXRbhpV09Jlnx6dz3HCtyPmw",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCqhigQpZE3a0rPtbJV2sHuZACmqTD6hy97Gdn",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCqhigQpZE3a0rPtbJV2sHuZACmqTD6hy97Gdn",
    chapters: [
      "Physical Geography",
      "Economic Geography",
      "Environmental Issues",
      "Map Skills"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "13.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Physics
  {

    id: "phy-g9",
    title: "Physics Grade 9",
    description: "Official Grade 9 Physics textbook covering basic concepts in mechanics, heat, light, and sound.",
    grade: "grade-9",
    subject: "Physics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonjtrdHA6XpZqglum0DUt2fPOzA13HYbhrCTk5",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCQfBgvq90JnGoIbVtPUXSQm52WKDfd6Tiyx43",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCQfBgvq90JnGoIbVtPUXSQm52WKDfd6Tiyx43",
    chapters: [
      "Mechanics",
      "Heat",
      "Light",
      "Sound",
      "Electricity"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "phy-g10",
    title: "Physics Grade 10",
    description: "Official Grade 10 Physics textbook covering advanced concepts in mechanics, heat, light, and sound.",
    grade: "grade-10",
    subject: "Physics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonXM5mKDHq9tLwn1SCQh6veo5dMrJDYOTZHzKW",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCwkBhvR6PLatv3qh8oIlDJeb92OZcnTQ4EViY",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCwkBhvR6PLatv3qh8oIlDJeb92OZcnTQ4EViY",
    chapters: [
      "Mechanics",
      "Heat",
      "Light",
      "Sound",
      "Electricity"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "phy-g11",
    title: "Physics Grade 11",
    description: "Official Grade 11 Physics textbook covering advanced concepts in mechanics, heat, light, and sound.",
    grade: "grade-11",
    subject: "Physics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonl9Fn1Ly6FLtMDgqsOrEwX1mhJpGWuBZPYn4Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMHLF9glMKQDVz97SNsiJqGurTt2EaIywXbRx",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMHLF9glMKQDVz97SNsiJqGurTt2EaIywXbRx",
    chapters: [
      "Mechanics",
      "Heat",
      "Light",
      "Sound",
      "Electricity"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "phy-g12",
    title: "Physics Grade 12",
    description: "Official Grade 12 Physics textbook covering advanced concepts in mechanics, heat, light, and sound.",
    grade: "grade-12",
    subject: "Physics",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonO0pywx93AxHSTm5Dk0LM7JFX6QIaBNiVucjU",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCx4UEpS2Oor5JfVEwxPzHZF6bANu2DaQ08isS",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCx4UEpS2Oor5JfVEwxPzHZF6bANu2DaQ08isS",
    chapters: [
      "Mechanics",
      "Heat",
      "Light",
      "Sound",
      "Electricity"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // ICT
  {
    id: "ict-g9",
    title: "ICT Grade 9",
    description: "Official Grade 9 ICT textbook covering computer hardware, software, networking, and programming.",
    grade: "grade-9",
    subject: "ICT",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonjhw9C96XpZqglum0DUt2fPOzA13HYbhrCTk5",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCLVBsbQMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCLVBsbQMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    chapters: [
      "Computer Hardware",
      "Software",
      "Networking",
      "Programming"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "ict-g10",
    title: "ICT Grade 10",
    description: "Official Grade 10 ICT textbook covering advanced computer hardware, software, networking, and programming.",
    grade: "grade-10",
    subject: "ICT",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonskhU0YK9nSywGpiR1sfCdDZt7uNlMKPk8Ac6",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCxqtE1vB2Oor5JfVEwxPzHZF6bANu2DaQ08is",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCxqtE1vB2Oor5JfVEwxPzHZF6bANu2DaQ08is",
    chapters: [
      "Computer Hardware",
      "Software",
      "Networking",
      "Programming"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"

  },
  {

    id: "ict-g11",
    title: "ICT Grade 11",
    description: "Official Grade 11 ICT textbook covering advanced computer hardware, software, networking, and programming.",
    grade: "grade-11",
    subject: "ICT",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonHdEx1S68mk6YsiI1uXRlfd0H9BzeK8VgjOZh",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCAgUiCPm1QWfbqNcla7URLp8vs0ogw532IuGY",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCAgUiCPm1QWfbqNcla7URLp8vs0ogw532IuGY",
    chapters: [
      "Computer Hardware",
      "Software",
      "Networking",
      "Programming"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "ict-g12",
    title: "ICT Grade 12",
    description: "Official Grade 12 ICT textbook covering advanced computer hardware, software, networking, and programming.",
    grade: "grade-12",
    subject: "ICT",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonhVxptJ3Sa3D0qbfy2U1nPkvtWsuEgwd5IV9Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCvQu9De9VpbzKWrRkjD3TXs2O8yxtSu5PZqN0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCvQu9De9VpbzKWrRkjD3TXs2O8yxtSu5PZqN0",
    chapters: [
      "Computer Hardware",
      "Software",
      "Networking",
      "Programming"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Biology
  {

    id: "bio-g9",
    title: "Biology Grade 9",
    description: "Official Grade 9 Biology textbook covering basic concepts in cell biology, genetics, and ecology.",
    grade: "grade-9",
    subject: "Biology",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon87D1IU0ahPs61p79rS4lCbezU23GBfdIoAqi",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCL2uRNPMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCL2uRNPMo8MQtUL7na4JPGNX3uBlOcgZHmIq0",
    chapters: [
      "Cell Biology",
      "Genetics",
      "Ecology",
      "Human Biology",
      "Plant Biology"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "bio-g10",
    title: "Biology Grade 10",
    description: "Official Grade 10 Biology textbook covering advanced concepts in cell biology, genetics, and ecology.",
    grade: "grade-10",
    subject: "Biology",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonWyKEQbPM5NifXRbhpV09Jlnx6dz3HCtyPmw4",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCJJiVZ6YGleqZD3uXwVQ1HmAB2ghIoK8LjCrN",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCJJiVZ6YGleqZD3uXwVQ1HmAB2ghIoK8LjCrN",
    chapters: [
      "Cell Biology",
      "Genetics",
      "Ecology",
      "Human Biology",
      "Plant Biology"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "bio-g11",
    title: "Biology Grade 11",
    description: "Official Grade 11 Biology textbook covering advanced concepts in cell biology, genetics, and ecology.",
    grade: "grade-11",
    subject: "Biology",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonMyVFKOoulvNQVLTqnDPa74buyR8EBUSYsrH1",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCElFqHTeLIuaK8OpUEwlNM5C1FRTkJZ0b2xnm",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCElFqHTeLIuaK8OpUEwlNM5C1FRTkJZ0b2xnm",
    chapters: [
      "Cell Biology",
      "Genetics",
      "Ecology",
      "Human Biology",
      "Plant Biology"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",

    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "bio-g12",
    title: "Biology Grade 12",
    description: "Official Grade 12 Biology textbook covering advanced concepts in cell biology, genetics, and ecology.",
    grade: "grade-12",
    subject: "Biology",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon78EnjQuXM8oBivR5lJeLqEfscSgphWtk0uPj",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC5tRXW8U94XsBygoGh3WFTNrkwZ28bPSp7caR",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC5tRXW8U94XsBygoGh3WFTNrkwZ28bPSp7caR",
    chapters: [
      "Cell Biology",
      "Genetics",
      "Ecology",
      "Human Biology",
      "Plant Biology"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Chemistry

  {
    id: "chem-g9",
    title: "Chemistry Grade 9",
    description: "Official Grade 9 Chemistry textbook covering basic concepts in matter, atoms, and chemical reactions.",
    grade: "grade-9",
    subject: "Chemistry",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonKhdGHZmsNiblgp971nR5dZQMLachyWfeOojY",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCtbm3rSAzXJsGf6PKyWr21U5HCT7SMbuF89aO",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCtbm3rSAzXJsGf6PKyWr21U5HCT7SMbuF89aO",
    chapters: [
      "Matter",
      "Atoms",
      "Chemical Reactions",
      "Acids and Bases",
      "Organic Chemistry"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 340,
    fileSize: "78.75 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  {
    id: "chem-g10",
    title: "Chemistry Grade 10",
    description: "Official Grade 10 Chemistry textbook covering advanced concepts in matter, atoms, and chemical reactions.",
    grade: "grade-10",
    subject: "Chemistry",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonvMFcBqQWN4SU9fPxleuB8sh3oEQKrDY5nq2p",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMw30NNlMKQDVz97SNsiJqGurTt2EaIywXbRx",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMw30NNlMKQDVz97SNsiJqGurTt2EaIywXbRx",
    chapters: [
      "Matter",
      "Atoms",
      "Chemical Reactions",
      "Acids and Bases",
      "Organic Chemistry"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.3 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "chem-g11",
    title: "Chemistry Grade 11",
    description: "Official Grade 11 Chemistry textbook covering advanced concepts in matter, atoms, and chemical reactions.",
    grade: "grade-11",
    subject: "Chemistry",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonbjtiYuVLIYCH9hoOaXyzr2n5mwtKuEx4lN8Z",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCyBMbWTKuBpl3j2NOHxcUw9q1ybeJigrh0PRW",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCyBMbWTKuBpl3j2NOHxcUw9q1ybeJigrh0PRW",
    chapters: [
      "Matter",
      "Atoms",
      "Chemical Reactions",
      "Acids and Bases",
      "Organic Chemistry"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 360,
    fileSize: "19.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  {
    id: "chem-g12",
    title: "Chemistry Grade 12",
    description: "Official Grade 12 Chemistry textbook covering advanced concepts in matter, atoms, and chemical reactions.",
    grade: "grade-12",
    subject: "Chemistry",
    stream: "Natural Science",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonyjL9yX91ZDQPx5IFmbJzBhN1T8YinMO2RvKE",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCEm3ypyLIuaK8OpUEwlNM5C1FRTkJZ0b2xnmH",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCEm3ypyLIuaK8OpUEwlNM5C1FRTkJZ0b2xnmH",
    chapters: [
      "Matter",
      "Atoms",
      "Chemical Reactions",
      "Acids and Bases",
      "Organic Chemistry"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 400,
    fileSize: "21.9 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Civics and Ethical Education
  {

    id: "civ-g9",
    title: "Civics and Ethical Education Grade 9",
    description: "Official Grade 9 Civics and Ethical Education textbook covering governance, rights, and responsibilities.",
    grade: "grade-9",
    subject: "Civics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonMytWBykulvNQVLTqnDPa74buyR8EBUSYsrH1",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCCCJj6Pvcgo9pPINwD7nZ21iY0jUkTVeCfmGz",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCCCJj6Pvcgo9pPINwD7nZ21iY0jUkTVeCfmGz",
    chapters: [
      "Governance",
      "Rights",
      "Responsibilities",
      "Ethical Education",
      "Civic Education"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "15.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "civ-g10",
    title: "Civics and Ethical Education Grade 10",
    description: "Official Grade 10 Civics and Ethical Education textbook covering governance, rights, and responsibilities.",
    grade: "grade-10",
    subject: "Civics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonhWTjuR3Sa3D0qbfy2U1nPkvtWsuEgwd5IV9Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCUMU8BEGeZ5tLdCkVrwcTpBn10HRMYNlPQ2ID",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCUMU8BEGeZ5tLdCkVrwcTpBn10HRMYNlPQ2ID",
    chapters: [
      "Governance",
      "Rights",
      "Responsibilities",
      "Ethical Education",
      "Civic Education"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "15.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  {

    id: "civ-g11",
    title: "Civics and Ethical Education Grade 11",
    description: "Official Grade 11 Civics and Ethical Education textbook covering governance, rights, and responsibilities.",
    grade: "grade-11",
    subject: "Civics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonZpCOUaVtNeArf0UXY4ObtwumDC2dJ9EclvaM",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC51AnvfU94XsBygoGh3WFTNrkwZ28bPSp7caR",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC51AnvfU94XsBygoGh3WFTNrkwZ28bPSp7caR",
    chapters: [
      "Governance",
      "Rights",
      "Responsibilities",
      "Ethical Education",
      "Civic Education"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "civ-g12",
    title: "Civics and Ethical Education Grade 12",
    description: "Official Grade 12 Civics and Ethical Education textbook covering governance, rights, and responsibilities.",
    grade: "grade-12",
    subject: "Civics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon3cgXUd2JOPxv6d9XFKH2Iy1WTpG3MNEufmqU",
    downloadUrl: "/books/civ-g12.pdf",
    pdfUrl: "https://uploadthing.com/Grade12-civics.pdf",
    chapters: [
      "Governance",
      "Rights",
      "Responsibilities",
      "Ethical Education",
      "Civic Education"
    ],
    recentlyViewed: true,

    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Economics
  {
    id: "eco-g9",
    title: "Economics Grade 9",
    description: "Official Grade 9 Economics textbook covering basic concepts in microeconomics and macroeconomics.",
    grade: "grade-9",
    subject: "Economics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon1vEKLaGuaMrEK8b97OlXsSzdjv4hkAUxeJqi",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCmDuExldHY7sW1efqpDQzLjZvCrxao35FyiRA",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCmDuExldHY7sW1efqpDQzLjZvCrxao35FyiRA",
    chapters: [
      "Microeconomics",
      "Macroeconomics",
      "Economic Systems",
      "Economic Development",
      "International Trade"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "15.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "eco-g10",
    title: "Economics Grade 10",
    description: "Official Grade 10 Economics textbook covering advanced concepts in microeconomics and macroeconomics.",
    grade: "grade-10",
    subject: "Economics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonxEy3UaDc9jh47KXBGEAzTb8OJpqrgPVu1iLC",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCR5YoD9Cz9goqFQaSPpAxVvli27ycb6GnOIwT",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCR5YoD9Cz9goqFQaSPpAxVvli27ycb6GnOIwT",
    chapters: [
      "Microeconomics",
      "Macroeconomics",
      "Economic Systems",
      "Economic Development",
      "International Trade"
    ],
    recentlyViewed: true,

    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "eco-g11",
    title: "Economics Grade 11",
    description: "Official Grade 11 Economics textbook covering advanced concepts in microeconomics and macroeconomics.",
    grade: "grade-11",
    subject: "Economics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonuC68Bglm0uR9PxOp3wUXjEsLI4QyHAkBbqfD",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC6Dy4fMunqREUOwgtyz2NS1poruWV7Y6GF0a3",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC6Dy4fMunqREUOwgtyz2NS1poruWV7Y6GF0a3",
    chapters: [
      "Microeconomics",
      "Macroeconomics",
      "Economic Systems",
      "Economic Development",
      "International Trade"
    ],
    recentlyViewed: true,

    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {

    id: "eco-g12",
    title: "Economics Grade 12",
    description: "Official Grade 12 Economics textbook covering advanced concepts in microeconomics and macroeconomics.",
    grade: "grade-12",
    subject: "Economics",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonhCqyFq3Sa3D0qbfy2U1nPkvtWsuEgwd5IV9Q",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC6Dy4fMunqREUOwgtyz2NS1poruWV7Y6GF0a3",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC6Dy4fMunqREUOwgtyz2NS1poruWV7Y6GF0a3",
    chapters: [
      "Microeconomics",
      "Macroeconomics",
      "Economic Systems",
      "Economic Development",
      "International Trade"
    ],
    recentlyViewed: true,

    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "18.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // History
  {
    id: "his-g9",
    title: "History Grade 9",
    description: "Official Grade 9 History textbook covering major events in world history and Ethiopian history.",
    grade: "grade-9",
    subject: "History",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonmH8KOG37gGwQ5PWeIdTkFrE96cfJbVL3Z1O2",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCHk6DYdTrUi9LPFvS62V8KzgGkMOXJcx0Bj1Z",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCHk6DYdTrUi9LPFvS62V8KzgGkMOXJcx0Bj1Z",
    chapters: [
      "Early Civilizations",
      "Medieval History",
      "The Renaissance",
      "Modern History",
      "World War I & II"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "9.66 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "his-g10",
    title: "History Grade 10",
    description: "Official Grade 10 History textbook covering key events in world and Ethiopian history from the 19th century.",
    grade: "grade-10",
    subject: "History",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTontS1SwmiXeYcgSNJGz2mDivfFloEPAV0pC4xh",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMy8UcgdlMKQDVz97SNsiJqGurTt2EaIywXbR",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCMy8UcgdlMKQDVz97SNsiJqGurTt2EaIywXbR",
    chapters: [
      "Industrial Revolution",
      "World War I",
      "The Interwar Period",
      "World War II",
      "Postwar Europe"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 320,
    fileSize: "11.28 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "his-g11",
    title: "History Grade 11",
    description: "Official Grade 11 History textbook covering world and Ethiopian history from the 20th century to present.",
    grade: "grade-11",
    subject: "History",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonsyZ7VFK9nSywGpiR1sfCdDZt7uNlMKPk8Ac6",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCvQ9biGPVpbzKWrRkjD3TXs2O8yxtSu5PZqN0",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCvQ9biGPVpbzKWrRkjD3TXs2O8yxtSu5PZqN0",
    chapters: [
      "The Cold War",
      "The Rise of Globalization",
      "Political Movements",
      "Social Movements",
      "Contemporary World History"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "12.5 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "his-g12",
    title: "History Grade 12",
    description: "Official Grade 12 History textbook covering advanced topics in world history, Ethiopia's history, and modern political studies.",
    grade: "grade-12",
    subject: "History",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonioOqv2p7TpzRtUysOSHYhKIw4rVPZeA9DXWm",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCJfQzf9YGleqZD3uXwVQ1HmAB2ghIoK8LjCrN",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCJfQzf9YGleqZD3uXwVQ1HmAB2ghIoK8LjCrN",
    chapters: [
      "Post-Colonial Africa",
      "The History of Ethiopia",
      "Global Political Systems",
      "International Relations",
      "Contemporary History"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 350,
    fileSize: "14.0 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // HPE (Health and Physical Education)
  {
    id: "hpe-g9",
    title: "Health and Physical Education Grade 9",
    description: "Official Grade 9 Health and Physical Education textbook covering topics in physical fitness, health education, and personal well-being.",
    grade: "grade-9",
    subject: "HPE",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonvUaL51WN4SU9fPxleuB8sh3oEQKrDY5nq2pT",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC9B3BebI8uZqeSw0R15jrKJzXHNgbxc2lGh3O",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRC9B3BebI8uZqeSw0R15jrKJzXHNgbxc2lGh3O",
    chapters: [
      "Introduction to Physical Education",
      "Personal Fitness",
      "Healthy Living",
      "Nutrition",
      "Mental Health"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 280,
    fileSize: "6.35 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "hpe-g10",
    title: "Health and Physical Education Grade 10",
    description: "Official Grade 10 Health and Physical Education textbook covering advanced topics in health, fitness, and physical activity.",
    grade: "grade-10",
    subject: "HPE",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonoF234tni8MIw0ugZWsQx7NBE5HDveRCLSt4n",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCsErtSEy2CKDGk0dtSWmPzaBuQxXJi5Nhr1Eo",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCsErtSEy2CKDGk0dtSWmPzaBuQxXJi5Nhr1Eo",
    chapters: [
      "Advanced Physical Education",
      "Sports Training",
      "Nutrition and Health",
      "Health Education",
      "Mental and Emotional Health"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "English",
    pages: 300,
    fileSize: "9.48 MB",
    curriculum: "Ethiopian Secondary Education"
  },

  // Amharic

  {
    id: "amh-g9",
    title: "Amharic Grade 9",
    description: "Official Grade 9 Amharic textbook covering reading, writing, and grammar.",
    grade: "grade-9",
    subject: "Amharic",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTon01953zdtgsOSvlC3ZRu6mGwVNPdpoTJjUBLz",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCkV6Jnf7bvDXNE2ShaL1O07Plm8rTHzCVIKoi",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCkV6Jnf7bvDXNE2ShaL1O07Plm8rTHzCVIKoi",
    chapters: [
      "Reading Comprehension",
      "Grammar",
      "Writing Skills",
      "Literature",
      "Poetry"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "Amharic",
    pages: 320,
    fileSize: "17.48 MB",
    curriculum: "Ethiopian Secondary Education"
  },
  {
    id: "amh-g10",
    title: "Amharic Grade 10",
    description: "Official Grade 10 Amharic textbook covering advanced reading, writing, and grammar topics.",
    grade: "grade-10",
    subject: "Amharic",
    stream: "All Streams",
    type: "Textbook",
    format: "PDF",
    coverUrl: "https://62f44o13z5.ufs.sh/f/FeiJqxS7QTonPzqYswMYTaBQDenvo2i39xbjSXwcslRzgCpt",
    downloadUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCXdorZDBkChtfvgWnwij7TOJbZLsMmeX50aY2",
    pdfUrl: "https://rhosttuy6t.ufs.sh/f/ZOv8L73t4xRCXdorZDBkChtfvgWnwij7TOJbZLsMmeX50aY2",
    chapters: [
      "Advanced Grammar",
      "Literary Criticism",
      "Poetry and Prose",
      "Amharic Composition",
      "Reading and Writing in Context"
    ],
    recentlyViewed: true,
    favorite: false,
    publisher: "Ministry of Education, Ethiopia",
    publishYear: 2024,
    language: "Amharic",
    pages: 350,
    fileSize: "18.72 MB",
    curriculum: "Ethiopian Secondary Education"
  },
];
