import { Exam } from "./types"

export const exams: Exam[] = [
    {
        id: "natural-math-2024",
        subject: "Mathematics",
        stream: "Natural",
        year: 2024,
        description: "Grade 12 Natural Science Mathematics Entrance Exam",
        duration: 180,
        questions: 65,
        attempts: 1250,
        averageScore: 72,
    },
    {
        id: "natural-physics-2024",
        subject: "Physics",
        stream: "Natural",
        year: 2024,
        description: "Grade 12 Natural Science Physics Entrance Exam",
        duration: 150,
        questions: 50,
        attempts: 980,
        averageScore: 68,
    },
    {
        id: "social-history-2024",
        subject: "History",
        stream: "Social",
        year: 2024,
        description: "Grade 12 Social Science History Entrance Exam",
        duration: 120,
        questions: 45,
        attempts: 850,
        averageScore: 75,
    },
    // Biology
    {
        id: "natural-biology-2024",
        subject: "Biology",
        stream: "Natural",
        year: 2024,
        description: "Grade 12 Natural Science Biology Entrance Exam",
        duration: 150,
        questions: 55,
        attempts: 1100,
        averageScore: 70,
    },
    {
        id: "social-geography-2024",
        subject: "Geography",
        stream: "Social",
        year: 2024,
        description: "Grade 12 Social Science Geography Entrance Exam",
        duration: 120,
        questions: 45,
        attempts: 920,
        averageScore: 70,
    },
]