import biologyQuestions2017 from "./data/practice-questions/biology";
import { PracticeSet } from "./types/practice";

export const practiceData: PracticeSet[] = [
  {
    id: "math-entrance-1",
    title: "Algebra Practice Test 1",
    subject: "Mathematics",
    topic: "Algebra",
    difficulty: "medium",
    questionCount: 60,
    timeLimit: 180,
    questions: [],
    attempts: 1250,
    averageScore: 72,
  },
  {
    id: "biology-micro-organisms-1",
    title: "Biology: Micro-organisms",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "hard",
    questionCount: 50,
    timeLimit: 180,
    questions: biologyQuestions2017,
    attempts: 980,
    averageScore: 68,
  },
  {
    id: "chemistry-organic-1",
    title: "Organic Chemistry",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    difficulty: "hard",
    questionCount: 30,
    timeLimit: 90,
    questions: [],
    averageScore: 65,
    attempts: 850,
  },
  {
    id: "biology-systems-1",
    title: "Biological Systems",
    subject: "Biology",
    topic: "Biological Systems",
    difficulty: "easy",
    questionCount: 45,
    timeLimit: 120,
    questions: [],
    averageScore: 75,
    attempts: 720,
  },
  {
    id: "p1",
    title: "Calculus Fundamentals",
    subject: "Mathematics",
    topic: "Calculus",
    difficulty: "medium",
    questionCount: 20,
    timeLimit: 45,
    questions: [],
    attempts: 156,
    averageScore: 72
  },
  {
    id: "p2",
    title: "Newton's Laws Practice",
    subject: "Physics",
    topic: "Mechanics",
    difficulty: "easy",
    questionCount: 15,
    timeLimit: 30,
    questions: [],
    attempts: 234,
    averageScore: 68
  },
  {
    id: "p3",
    title: "Organic Chemistry Challenge",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    difficulty: "hard",
    questionCount: 25,
    timeLimit: 60,
    questions: [],
    attempts: 89,
    averageScore: 65
  }
];