import chemistryQuestions from "./data/practice-questions/chemistry/chemistry-25";
import chemistryG12Questions from "./data/practice-questions/chemistry/chemistry-u1-and-2";
import economicsUnit1Questions from "./data/practice-questions/economics/grade12-unit-1";
import economicsUnit2Questions from "./data/practice-questions/economics/grade12-unit-2";
import { historyQuestionsUnit1, historyQuestionsUnit2 } from "./data/practice-questions/history/history-g11";
import { historyQuestionsUnit1_and_2, historyQuestionsUnit1_and_2_continued } from "./data/practice-questions/history/grade12-unit1-and-2";
import mathQuestionsUnit1_and_2 from "./data/practice-questions/math/grade12-u1and2";
import { physicsUnit1Questions, physicsUnit2Questions } from "./data/practice-questions/physics/physics-g11";
import { PracticeSet } from "./types/practice";
import { biologyQuestionsUnit1_and_2, biologyQuestionsUnit3and4_2024 } from "@/lib/data/practice-questions/biology/grade11";

export const practiceData: PracticeSet[] = [
  // mathQuestionsUnit1_and_2 (Securence and Series and Intro to calculus) 80 questions
  {
    id: "math-u1-and-2",
    title: "Math G-12 Unit 1 and 2",
    subject: "Mathematics",
    topic: "Sequences & Series and Introduction to Calculus",
    difficulty: "medium",
    questionCount: 80,
    timeLimit: 120,
    questions: mathQuestionsUnit1_and_2.flat(),
    attempts: 0,
    averageScore: 0,
  },
  {
    id: "history-u1-and-2",
    title: "Part || History G-12 Unit 1 and 2",
    subject: "History",
    topic: "Development of Capitalism, Nationalism, and Colonialism",
    difficulty: "medium",
    questionCount: historyQuestionsUnit1_and_2_continued.length,
    timeLimit: 60,
    questions: historyQuestionsUnit1_and_2_continued.flat(),
    attempts: 0,
    averageScore: 0,
  },
  {
    id: "history-u1-and-2",
    title: "History G-12 Unit 1 and 2",
    subject: "History",
    topic: "Development of Capitalism, Nationalism, and Colonialism",
    difficulty: "medium",
    questionCount: historyQuestionsUnit1_and_2.length,
    timeLimit: 120,
    questions: historyQuestionsUnit1_and_2.flat(),
    attempts: 0,
    averageScore: 0,
  },
  // biologyQuestionsUnit3and4_2024 (Enzymes and Genetics) 100 questions
  {
    id: "biology-u3-and-4",
    title: "Biology G-11 Unit 3 and 4",
    subject: "Biology",
    topic: "Enzymes & Genetics",
    difficulty: "medium",
    questionCount: 100,
    timeLimit: 120,
    questions: biologyQuestionsUnit3and4_2024.flat(),
    attempts: 0,
    averageScore: 0,
  },
  // biologyQuestionsUnit1_and_2 Unit 1 (Biology and Technology and 2 (Animals)
  {
    id: "biology-u1-and-2",
    title: "Biology G-11 Unit 1 and 2",
    subject: "Biology",
    topic: "Biology and Technology & Animals",
    difficulty: "easy",
    questionCount: 50,
    timeLimit: 60,
    questions: biologyQuestionsUnit1_and_2.flat(),
    attempts: 0,
    averageScore: 0,
  },
  {
    id: "economics-u1",
    title: "Economics G-12 Unit 1",
    subject: "Economics",
    topic: "Fundamental Concepts of Macroeconomics",
    difficulty: "medium",
    questionCount: 20,
    timeLimit: 30,
    questions: economicsUnit1Questions,
    attempts: 0,
    averageScore: 0,
  },
  {
    id: "economics-u2",
    title: "Economics G-12 Unit 2",
    subject: "Economics",
    topic: "Aggregate Demand and Aggregate Supply Analysis",
    difficulty: "medium",
    questionCount: 20,
    timeLimit: 30,
    questions: economicsUnit2Questions,
    attempts: 0,
    averageScore: 0,
  },
  {
    id: "chemistry-entrance-1",
    title: "Chemistry Entrance Exam Practice",
    subject: "Chemistry",
    topic: "General Chemistry",
    difficulty: "medium",
    questionCount: 30,
    timeLimit: 40,
    questions: chemistryQuestions,
    attempts: 850,
    averageScore: 68,
  },
  {
    id: "chemistry-u1-and-2",
    title: "Chemistry G-12 Unit 1 and 2",
    subject: "Chemistry",
    topic: "General Chemistry",
    difficulty: "medium",
    questionCount: 10,
    timeLimit: 15,
    questions: chemistryG12Questions,
    attempts: 850,
    averageScore: 68,
  },
  {
    id: "history-g11-u1",
    title: "History G11 Unit 1",
    subject: "History",
    topic: "Historiography & Human Evolution",
    difficulty: "medium",
    questionCount: 20,
    timeLimit: 30, // Time limit in minutes
    questions: historyQuestionsUnit1,
    attempts: 0,
    averageScore: 0,
  },
  {
    id: "history-g11-u2",
    title: "History G11 Unit 2",
    subject: "History",
    topic: "Major Spots of Ancient World Civilizations",
    difficulty: "medium",
    questionCount: 30,
    timeLimit: 45,
    questions: historyQuestionsUnit2,
    attempts: 0,
    averageScore: 0,
  },
  {
    id: "physics-g11-u1",
    title: "Physics G11 Unit 1",
    subject: "Physics",
    topic: "Physics and Human Society",
    difficulty: "medium",
    questionCount: 5,
    timeLimit: 30,
    questions: physicsUnit1Questions,
    attempts: 0,
    averageScore: 0,
  },
  {
    id: "physics-g11-u2",
    title: "Physics G11 Unit 2",
    subject: "Physics",
    topic: "Vectors",
    difficulty: "medium",
    questionCount: 10,
    timeLimit: 45,
    questions: physicsUnit2Questions,
    attempts: 0,
    averageScore: 0,
  }

];
